server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://54.169.178.240:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: 
              - GET
              - PUT
              - POST
              - DELETE
      routes:
        - id: USER-SERVICE-SIGNIN
          uri: lb://UserService
          predicates:
            - Path=/auth/login,/users/register
        - id: USER-SERVICE
          uri: lb://UserService
          predicates:
            - Path=/users/** 
          filters:
            - AuthFilters
        - id: TODO-SERVICE
          uri: lb://TodoService
          predicates:
            - Path=/todos/**  
          filters:
            - AuthFilters
